name: Code Coverage Check - PR
on:
  pull_request:
    branches: ['main']
  schedule:
    - cron: '45 12 * * 0'


jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
       language: [ "javascript-typescript" ]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Init CodeQL
      uses: github/codeql-action/init@v3
      with:
        langauges: ${{matrix.language}}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}" 

    - name: Run Unit Tests
      run: mvn test
      
      
      
